### ISSUE TITLE
Confusion with rebinding of variables

### ISSUE THREAD

**Issue by MasonProtter** [JuliaStaging/JuliaVariables.jl#22] opened 2021-02-27 23:53 UTC
```julia
julia> ex = quote
           x = 2x + 1
       end;

julia> solve_from_local!(simplify_ex(ex))
:($(Expr(:scoped, (bounds = Var[@local x], freevars = Var[], bound_inits = Symbol[]), quote
    #= REPL[15]:2 =#
    @local x = (@global +)((@global *)(2, @local x), 1)
end)))
```
Here, `x` should be global because it's read from before it's rebound.

**Comment by thautwarm** [comment] 2021-02-28 09:45
Hi Mason, you could use `solve!` instead of `solve_from_local!` to assume the input AST has global scope.

**Comment by thautwarm** [comment] 2021-02-28 09:47
```julia
julia> solve!(simplify_ex(quote x = 2x + 1 end))
:($(Expr(:scoped, (bounds = Var[], freevars = Var[], bound_inits = Symbol[]), quote
    #= REPL[3]:1 =#
    @global x = (@global +)((@global *)(2, @global x), 1)
end)))
```

**Comment by MasonProtter** [comment] 2021-02-28 16:46
I don't think that's right, because I mean for this to be the inside of a function body or `let` block. If I use `solve!` instead of `solve_from_local!` then later, actual local variables I introduce are going to be global:
```julia
julia> ex = quote
           x = 2x + 1
           y = x - 1
       end;

julia> solve!(simplify_ex(ex))
:($(Expr(:scoped, (bounds = Var[], freevars = Var[], bound_inits = Symbol[]), quote
    #= REPL[42]:2 =#
    @global x = (@global +)((@global *)(2, @global x), 1)
    #= REPL[42]:3 =#
    @global y = (@global -)(@global x, 1)
end)))
``

**Comment by MasonProtter** [comment] 2021-02-28 16:52
If I stick the expression in a `let` block, I get a doubly wrong answer:
```julia
julia> ex = quote
           let
               x = 2x + 1
               y = x - 1
           end
       end;

julia> solve!(simplify_ex(ex))
:($(Expr(:scoped, (bounds = Var[], freevars = Var[], bound_inits = Symbol[]), quote
    #= REPL[44]:2 =#
    begin
        #= REPL[44]:3 =#
        @global x = (@global +)((@global *)(2, @global x), 1)
        #= REPL[44]:4 =#
        @global y = (@global -)(@global x, 1)
    end
end)))
```

**Comment by thautwarm** [comment] 2021-03-02 13:08
> If I stick the expression in a `let` block, I get a doubly wrong answer:
> 
> ```julia
> julia> ex = quote
>            let
>                x = 2x + 1
>                y = x - 1
>            end
>        end;
> 
> julia> solve!(simplify_ex(ex))
> :($(Expr(:scoped, (bounds = Var[], freevars = Var[], bound_inits = Symbol[]), quote
>     #= REPL[44]:2 =#
>     begin
>         #= REPL[44]:3 =#
>         @global x = (@global +)((@global *)(2, @global x), 1)
>         #= REPL[44]:4 =#
>         @global y = (@global -)(@global x, 1)
>     end
> end)))
> ```

I'm going to fix this.

**Comment by thautwarm** [comment] 2021-03-02 13:13
> I don't think that's right, because I mean for this to be the inside of a function body or `let` block. If I use `solve!` instead of `solve_from_local!` then later, actual local variables I introduce are going to be global:
> 
> ```julia
> julia> ex = quote
>            x = 2x + 1
>            y = x - 1
>        end;
> 
> julia> solve!(simplify_ex(ex))
> :($(Expr(:scoped, (bounds = Var[], freevars = Var[], bound_inits = Symbol[]), quote
>     #= REPL[42]:2 =#
>     @global x = (@global +)((@global *)(2, @global x), 1)
>     #= REPL[42]:3 =#
>     @global y = (@global -)(@global x, 1)
> end)))
> ``
> ```

I guess the problem is that the scoping rule you used to take is different from julia's.

```julia
julia> function f()
           x = 2x + 1
       end
f (generic function with 1 method)

julia> f()
ERROR: UndefVarError: x not defined
Stacktrace:
 [1] f() at .\REPL[4]:2
 [2] top-level scope at REPL[5]:1
```

Although you read `x` first, and you think it should be a global one, but global variables are **not writable** by default if it's not in the global scope.

**Comment by thautwarm** [comment] 2021-03-02 13:34
After bugfix empty binding in let blocks:

```julia
julia> ex = quote
                  let
                      x = 2x + 1
                      y = x - 1
                  end
              end;

julia> solve!(simplify_ex(ex))
:($(Expr(:scoped, (bounds = Var[], freevars = Var[], bound_inits = Symbol[]), quote
    #= REPL[4]:2 =#
    let
        $(Expr(:scoped, (bounds = Var[@local y, @local x], freevars = Var[], bound_inits = Symbol[]), quote
    #= REPL[4]:3 =#
    @local x = (@global +)((@global *)(2, @local x), 1)
    #= REPL[4]:4 =#
    @local y = (@global -)(@local x, 1)
end))
    end
end)))

julia> ex = quote
                  let x = 2x + 1
                      y = x - 1
                  end
              end;

julia> solve!(simplify_ex(ex))
:($(Expr(:scoped, (bounds = Var[], freevars = Var[], bound_inits = Symbol[]), quote
    #= REPL[6]:2 =#
    let x = (@global +)((@global *)(2, @global x), 1)
        $(Expr(:scoped, (bounds = Var[@local y, @local x], freevars = Var[], bound_inits = [:x]), quote
    #= REPL[6]:3 =#
    @local y = (@global -)(@local x, 1)
end))
    end
end)))
```

**Comment by MasonProtter** [comment] 2021-03-02 16:04
> I guess the problem is that the scoping rule you used to take is different from julia's.
> 
> ```julia
> julia> function f()
>            x = 2x + 1
>        end
> f (generic function with 1 method)
> 
> julia> f()
> ERROR: UndefVarError: x not defined
> Stacktrace:
>  [1] f() at .\REPL[4]:2
>  [2] top-level scope at REPL[5]:1
> ```
> 
> Although you read `x` first, and you think it should be a global one, but global variables are **not writable** by default if it's not in the global scope.

Oh I see! For some reason I though this worked:
```julia
julia> x = 1
1

julia> let 
           x = 2x + 1
       end
ERROR: UndefVarError: x not defined
Stacktrace:
 [1] top-level scope
   @ REPL[2]:2
```

My mistake, thank you for fixing the `let` issue and for explaining this to me, I appreciate it!

**Comment by thautwarm** [comment] 2021-03-04 04:59
You're welcome! 😄 
May you please close this issue if no issues now?

**Closed as completed** 2021-03-04 04:59 UTC
